### ISSUE TITLE
Change Scroll color

### ISSUE THREAD

**Issue by naothomachida** [codemaskinc/react-smart-scroller#85]
Hi there,

I'm looking for change de background color #2ecc71, can you help me?

I tried another way to hide de scroll bar with option withScroll, but no success

`<ReactSmartScroller draggable paginationConfig={{ withScroll: false }}>`

**Comment by GrzegorzTarnopolski** [comment]
@naothomachida Hello!

in order to change the background of the scroll track you can simply write

```
<ReactSmartScroller
    trackProps={{
      backgroundColor: 'blue'
    }}
  >
```

in order to change the color of the scroll you must create a new thumb, currently there is no option to change the color of initial thumb, if you would like so, let me know answering this comment and we shall add it :)

```
<ReactSmartScroller
    thumb={(
      <div
        style={{
          backgroundColor: 'green',
          width: 50,
          height: 10
        }}
      />
    )}
  >
```

**Comment by naothomachida** [comment]
@GrzegorzTarnopolski thanks! Solved using new thumb :)

This lib is topper
